name: Performance E2E Test Manual WorkFlow

on:
  workflow_dispatch:
    inputs:
      info:
        description: 'This workflow runs performance tests on multiple devices for both iOS and Android platforms'
        required: false
        type: string
      browserstack_app_url_android:
        description: 'BrowserStack Android App URL (bs://...)'
        required: true
        type: string
      browserstack_app_url_ios:
        description: 'BrowserStack iOS App URL (bs://...)'
        required: true
        type: string
      test_suite:
        description: 'Test suite to run (e.g., **/tests/*.spec.js for all tests)'
        required: false
        default: '**/tests/*.spec.js'
        type: string

permissions:
  contents: read
  id-token: write

env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  MM_TEST_ACCOUNT_SRP: ${{ secrets.MM_TEST_ACCOUNT_SRP }}
  TEST_SRP_1: ${{ secrets.TEST_SRP_1 }}
  TEST_SRP_2: ${{ secrets.TEST_SRP_2 }}
  TEST_SRP_3: ${{ secrets.TEST_SRP_3 }}

jobs:
  # Sequential Android Tests on Multiple Devices
  android-tests:
    name: Android Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        device:
          # High-end Devices
          - name: 'Samsung Galaxy S23 Ultra'
            os_version: '13.0'
            category: 'high'
          # - name: 'Google Pixel 8 Pro'
          #   os_version: '14.0'
          #   category: 'high'
          
          # # Medium Devices
          # - name: 'Samsung Galaxy A52'
          #   os_version: '11.0'
          #   category: 'medium'
          
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn setup

      - name: BrowserStack Env Setup
        uses: browserstack/github-actions/setup-env@4478e16186f38e5be07721931642e65a028713c3
        with:
          username: ${{ env.BROWSERSTACK_USERNAME }}
          access-key: ${{ env.BROWSERSTACK_ACCESS_KEY }}
          build-name: ${{ github.repository }}-${{ github.ref_name }}-android-${{ matrix.device.name }}-${{ matrix.device.os_version }}-${{ github.run_number }}
          project-name: ${{ github.repository }}

      - name: Setup BrowserStack Local
        uses: browserstack/github-actions/setup-local@4478e16186f38e5be07721931642e65a028713c3
        with:
          local-testing: start
          local-identifier: ${{ github.run_id }}
          local-args: --force-local --verbose
      
      - name: Wait for BrowserStack Local
        run: |
          echo "Waiting for BrowserStack Local to be ready..."
          sleep 30
          echo "BrowserStack Local should be ready now"
      
      - name: Set Android Test Environment
        run: |
          echo "Setting test environment for device: ${{ matrix.device.name }}"
          echo "BROWSERSTACK_DEVICE=${{ matrix.device.name }}" >> $GITHUB_ENV
          echo "BROWSERSTACK_OS_VERSION=${{ matrix.device.os_version }}" >> $GITHUB_ENV
          echo "BROWSERSTACK_ANDROID_APP_URL=${{ github.event.inputs.browserstack_app_url_android }}" >> $GITHUB_ENV
          echo "TEST_PLATFORM=android" >> $GITHUB_ENV
          echo "TEST_SUITE=${{ github.event.inputs.test_suite }}" >> $GITHUB_ENV
      
      - name: Run Android Tests on ${{ matrix.device.name }}
        env:
          BROWSERSTACK_LOCAL: true
          BROWSERSTACK_LOCAL_IDENTIFIER: ${{ github.run_id }}
        run: |
          echo "=== Testing ${{ matrix.device.name }} (${{ matrix.device.category }} Class) ==="
          echo "OS Version: ${{ matrix.device.os_version }}"
          echo "Category: ${{ matrix.device.category }}"
          echo "Branch: ${{ github.ref_name }}"
          
          yarn run-appwright:android-bs
      
      - name: Upload Android Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-test-results-${{ matrix.device.name }}-${{ matrix.device.os_version }}
          path: |
            test-reports/
            appwright-report/
          retention-days: 7

  # Sequential iOS Tests on Multiple Devices
  ios-tests:
    name: iOS Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        device:
          # High-end Devices
          - name: 'iPhone 14 Pro Max'
            os_version: '16.0'
            category: 'high'
          
          # # Medium Devices
          # - name: 'iPhone 12'
          #   os_version: '14.0'
          #   category: 'medium'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn setup

      - name: BrowserStack Env Setup
        uses: browserstack/github-actions/setup-env@4478e16186f38e5be07721931642e65a028713c3
        with:
          username: ${{ env.BROWSERSTACK_USERNAME }}
          access-key: ${{ env.BROWSERSTACK_ACCESS_KEY }}
          build-name: ${{ github.repository }}-${{ github.ref_name }}-ios-${{ matrix.device.name }}-${{ matrix.device.os_version }}-${{ github.run_number }}
          project-name: ${{ github.repository }}

      - name: Setup BrowserStack Local
        uses: browserstack/github-actions/setup-local@4478e16186f38e5be07721931642e65a028713c3
        with:
          local-testing: start
          local-identifier: ${{ github.run_id }}
          local-args: --force-local --verbose
      
      - name: Wait for BrowserStack Local
        run: |
          echo "Waiting for BrowserStack Local to be ready..."
          sleep 30
          echo "BrowserStack Local should be ready now"
      
      - name: Set iOS Test Environment
        run: |
          echo "Setting test environment for device: ${{ matrix.device.name }}"
          echo "BROWSERSTACK_DEVICE=${{ matrix.device.name }}" >> $GITHUB_ENV
          echo "BROWSERSTACK_OS_VERSION=${{ matrix.device.os_version }}" >> $GITHUB_ENV
          echo "BROWSERSTACK_IOS_APP_URL=${{ github.event.inputs.browserstack_app_url_ios }}" >> $GITHUB_ENV
          echo "TEST_SUITE=${{ github.event.inputs.test_suite }}" >> $GITHUB_ENV
      
      - name: Run iOS Tests on ${{ matrix.device.name }}
        env:
          BROWSERSTACK_LOCAL: true
          BROWSERSTACK_LOCAL_IDENTIFIER: ${{ github.run_id }}
        run: |
          echo "=== Testing ${{ matrix.device.name }} (${{ matrix.device.category }} Class) ==="
          echo "OS Version: ${{ matrix.device.os_version }}"
          echo "Category: ${{ matrix.device.category }}"
          echo "Branch: ${{ github.ref_name }}"
          if [ "${{ matrix.device.os_version }}" == "13" ] || [ "${{ matrix.device.os_version }}" == "11" ]; then
            echo "Warning: iOS ${{ matrix.device.os_version }} may not be supported by MetaMask app"
          fi
          
          yarn run-appwright:ios-bs
      
      - name: Upload iOS Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ios-test-results-${{ matrix.device.name }}-${{ matrix.device.os_version }}
          path: |
            test-reports/
            appwright-report/
          retention-days: 7

  # Results Gathering Job
  gather-results:
    name: Gather Test Results
    runs-on: ubuntu-latest
    needs: [android-tests, ios-tests]
    if: always()
    
    steps:
      - name: Download All Test Results
        uses: actions/download-artifact@v4
        with:
          path: test-results/
      
      - name: Generate Test Summary
        run: |
          echo "## Sequential Test Execution Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Execution Order" >> $GITHUB_STEP_SUMMARY
          echo "Tests were executed sequentially (one device at a time) for better resource management." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Device Matrix Overview" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### Android Devices (5 total) - Sequential Order:" >> $GITHUB_STEP_SUMMARY
          echo "1. **Samsung Galaxy S23 Ultra** (High Class) - Android 13" >> $GITHUB_STEP_SUMMARY
          echo "2. **Google Pixel 8 Pro** (High Class) - Android 14" >> $GITHUB_STEP_SUMMARY
          echo "3. **Samsung Galaxy A52s 5G** (Medium Class) - Android 12" >> $GITHUB_STEP_SUMMARY
          echo "4. **Samsung Galaxy A32** (Low Class) - Android 11" >> $GITHUB_STEP_SUMMARY
          echo "5. **TECNO KI5k** (Low Class) - Android 11" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### iOS Devices (3 total) - Sequential Order:" >> $GITHUB_STEP_SUMMARY
          echo "1. **iPhone 14 Pro Max** (High Class) - iOS 16" >> $GITHUB_STEP_SUMMARY
          echo "2. **iPhone 11** (Medium Class) - iOS 13 - ⚠️ iOS 13 not supported by MetaMask" >> $GITHUB_STEP_SUMMARY
          echo "3. **iPhone 8** (Low Class) - iOS 11 - ⚠️ iOS 11 not supported by MetaMask" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Test Results" >> $GITHUB_STEP_SUMMARY
          echo "Check the artifacts above for detailed test reports from each device." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Important Notes" >> $GITHUB_STEP_SUMMARY
          echo "- Tests run sequentially: Device A → Device B → Device C, etc." >> $GITHUB_STEP_SUMMARY
          echo "- iOS 13 and iOS 11 devices may fail due to MetaMask app compatibility" >> $GITHUB_STEP_SUMMARY
          echo "- Uses matrix strategy to dynamically update appwright config for each device" >> $GITHUB_STEP_SUMMARY
      
      - name: Check Test Results
        run: |
          if [ "${{ needs.android-tests.result }}" == "failure" ] || [ "${{ needs.ios-tests.result }}" == "failure" ]; then
            echo "Some tests failed. Check the individual job results above."
            echo "Note: iOS 13 and iOS 11 failures are expected due to MetaMask app compatibility."
            exit 1
          else
            echo "All test jobs completed successfully!"
          fi
